before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - 
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "linux" }}Linux
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}x86_64
      {{- else }}{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'
nfpms:
  -
    package_name: sysload-exporter
    homepage: https://github.com/egmc/sysload_exporter
    maintainer: Sohei Iwahori
    description: "sysload exporter is prometheus style, go implementation of https://github.com/gree/sysload"
    license: GPL-2.0
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
    contents:
      - src: "packaging/deb/systemd/sysload-exporter.service"
        dst: "/usr/lib/systemd/system/sysload-exporter.service"
    bindir: /usr/bin
    scripts:
      postinstall: "packaging/scripts/postinstall"
      postremove: "packaging/scripts/postremove"
      preremove: "packaging/scripts/preremove"
